spring:
  application:
    name: rt-example-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rt_example_db}
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_pass}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql
